ALTER TABLE teams ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS facebook_url VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS instagram_url VARCHAR(255);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS whatsapp_phone VARCHAR(50);
ALTER TABLE teams ADD COLUMN IF NOT EXISTS call_phone VARCHAR(50);
